# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `optimist` gem.
# Please instead update this file by running `bin/tapioca gem optimist`.


# pkg:gem/optimist#lib/optimist.rb:10
module Optimist
  private

  # Informs the user that their usage of 'arg' was wrong, as detailed by
  # 'msg', and dies. Example:
  #
  #   options do
  #     opt :volume, :default => 0.0
  #   end
  #
  #   die :volume, "too loud" if opts[:volume] > 10.0
  #   die :volume, "too soft" if opts[:volume] < 0.1
  #
  # In the one-argument case, simply print that message, a notice
  # about -h, and die. Example:
  #
  #   options do
  #     opt :whatever # ...
  #   end
  #
  #   Optimist::die "need at least one filename" if ARGV.empty?
  #
  # An exit code can be provide if needed
  #
  #   Optimist::die "need at least one filename", -2 if ARGV.empty?
  #
  # pkg:gem/optimist#lib/optimist.rb:1246
  def die(arg, msg = T.unsafe(nil), error_code = T.unsafe(nil)); end

  # Displays the help message and dies. Example:
  #
  #   options do
  #     opt :volume, :default => 0.0
  #     banner <<-EOS
  #   Usage:
  #          #$0 [options] <name>
  #   where [options] are:
  #   EOS
  #   end
  #
  #   Optimist::educate if ARGV.empty?
  #
  # pkg:gem/optimist#lib/optimist.rb:1266
  def educate; end

  # The easy, syntactic-sugary entry method into Optimist. Creates a Parser,
  # passes the block to it, then parses +args+ with it, handling any errors or
  # requests for help or version information appropriately (and then exiting).
  # Modifies +args+ in place. Returns a hash of option values.
  #
  # The block passed in should contain zero or more calls to +opt+
  # (Parser#opt), zero or more calls to +text+ (Parser#text), and
  # probably a call to +version+ (Parser#version).
  #
  # The returned block contains a value for every option specified with
  # +opt+.  The value will be the value given on the commandline, or the
  # default value if the option was not specified on the commandline. For
  # every option specified on the commandline, a key "<option
  # name>_given" will also be set in the hash.
  #
  # Example:
  #
  #   require 'optimist'
  #   opts = Optimist::options do
  #     opt :monkey, "Use monkey mode"                    # a flag --monkey, defaulting to false
  #     opt :name, "Monkey name", :type => :string        # a string --name <s>, defaulting to nil
  #     opt :num_limbs, "Number of limbs", :default => 4  # an integer --num-limbs <i>, defaulting to 4
  #   end
  #
  #   ## if called with no arguments
  #   p opts # => {:monkey=>false, :name=>nil, :num_limbs=>4, :help=>false}
  #
  #   ## if called with --monkey
  #   p opts # => {:monkey=>true, :name=>nil, :num_limbs=>4, :help=>false, :monkey_given=>true}
  #
  # Settings:
  #   Optimist::options and Optimist::Parser.new accept +settings+ to control how
  #   options are interpreted.  These settings are given as hash arguments, e.g:
  #
  #   opts = Optimist::options(ARGV, exact_match: false) do
  #     opt :foobar, 'messed up'
  #     opt :forget, 'forget it'
  #   end
  #
  #  +settings+ include:
  #  * :exact_match  : (default=true) Allow minimum unambigous number of characters to match a long option
  #  * :suggestions  : (default=true) Enables suggestions when unknown arguments are given and DidYouMean is installed.  DidYouMean comes standard with Ruby 2.3+
  #  * :implicit_short_opts : (default=true) Short options will only be created where explicitly defined.  If you do not like short-options, this will prevent having to define :short=> :none for all of your options.
  #  Because Optimist::options uses a default argument for +args+, you must pass that argument when using the settings feature.
  #
  # See more examples at https://www.manageiq.org/optimist
  #
  # pkg:gem/optimist#lib/optimist.rb:1182
  def options(args = T.unsafe(nil), *a, &b); end

  # If Optimist::options doesn't do quite what you want, you can create a Parser
  # object and call Parser#parse on it. That method will throw CommandlineError,
  # HelpNeeded and VersionNeeded exceptions when necessary; if you want to
  # have these handled for you in the standard manner (e.g. show the help
  # and then exit upon an HelpNeeded exception), call your code from within
  # a block passed to this method.
  #
  # Note that this method will call System#exit after handling an exception!
  #
  # Usage example:
  #
  #   require 'optimist'
  #   p = Optimist::Parser.new do
  #     opt :monkey, "Use monkey mode"                     # a flag --monkey, defaulting to false
  #     opt :goat, "Use goat mode", :default => true       # a flag --goat, defaulting to true
  #   end
  #
  #   opts = Optimist::with_standard_exception_handling p do
  #     o = p.parse ARGV
  #     raise Optimist::HelpNeeded if ARGV.empty? # show help screen
  #     o
  #   end
  #
  # Requires passing in the parser object.
  #
  # pkg:gem/optimist#lib/optimist.rb:1212
  def with_standard_exception_handling(parser); end

  class << self
    # Informs the user that their usage of 'arg' was wrong, as detailed by
    # 'msg', and dies. Example:
    #
    #   options do
    #     opt :volume, :default => 0.0
    #   end
    #
    #   die :volume, "too loud" if opts[:volume] > 10.0
    #   die :volume, "too soft" if opts[:volume] < 0.1
    #
    # In the one-argument case, simply print that message, a notice
    # about -h, and die. Example:
    #
    #   options do
    #     opt :whatever # ...
    #   end
    #
    #   Optimist::die "need at least one filename" if ARGV.empty?
    #
    # An exit code can be provide if needed
    #
    #   Optimist::die "need at least one filename", -2 if ARGV.empty?
    #
    # pkg:gem/optimist#lib/optimist.rb:1275
    def die(arg, msg = T.unsafe(nil), error_code = T.unsafe(nil)); end

    # Displays the help message and dies. Example:
    #
    #   options do
    #     opt :volume, :default => 0.0
    #     banner <<-EOS
    #   Usage:
    #          #$0 [options] <name>
    #   where [options] are:
    #   EOS
    #   end
    #
    #   Optimist::educate if ARGV.empty?
    #
    # pkg:gem/optimist#lib/optimist.rb:1275
    def educate; end

    # The easy, syntactic-sugary entry method into Optimist. Creates a Parser,
    # passes the block to it, then parses +args+ with it, handling any errors or
    # requests for help or version information appropriately (and then exiting).
    # Modifies +args+ in place. Returns a hash of option values.
    #
    # The block passed in should contain zero or more calls to +opt+
    # (Parser#opt), zero or more calls to +text+ (Parser#text), and
    # probably a call to +version+ (Parser#version).
    #
    # The returned block contains a value for every option specified with
    # +opt+.  The value will be the value given on the commandline, or the
    # default value if the option was not specified on the commandline. For
    # every option specified on the commandline, a key "<option
    # name>_given" will also be set in the hash.
    #
    # Example:
    #
    #   require 'optimist'
    #   opts = Optimist::options do
    #     opt :monkey, "Use monkey mode"                    # a flag --monkey, defaulting to false
    #     opt :name, "Monkey name", :type => :string        # a string --name <s>, defaulting to nil
    #     opt :num_limbs, "Number of limbs", :default => 4  # an integer --num-limbs <i>, defaulting to 4
    #   end
    #
    #   ## if called with no arguments
    #   p opts # => {:monkey=>false, :name=>nil, :num_limbs=>4, :help=>false}
    #
    #   ## if called with --monkey
    #   p opts # => {:monkey=>true, :name=>nil, :num_limbs=>4, :help=>false, :monkey_given=>true}
    #
    # Settings:
    #   Optimist::options and Optimist::Parser.new accept +settings+ to control how
    #   options are interpreted.  These settings are given as hash arguments, e.g:
    #
    #   opts = Optimist::options(ARGV, exact_match: false) do
    #     opt :foobar, 'messed up'
    #     opt :forget, 'forget it'
    #   end
    #
    #  +settings+ include:
    #  * :exact_match  : (default=true) Allow minimum unambigous number of characters to match a long option
    #  * :suggestions  : (default=true) Enables suggestions when unknown arguments are given and DidYouMean is installed.  DidYouMean comes standard with Ruby 2.3+
    #  * :implicit_short_opts : (default=true) Short options will only be created where explicitly defined.  If you do not like short-options, this will prevent having to define :short=> :none for all of your options.
    #  Because Optimist::options uses a default argument for +args+, you must pass that argument when using the settings feature.
    #
    # See more examples at https://www.manageiq.org/optimist
    #
    # pkg:gem/optimist#lib/optimist.rb:1275
    def options(args = T.unsafe(nil), *a, &b); end

    # If Optimist::options doesn't do quite what you want, you can create a Parser
    # object and call Parser#parse on it. That method will throw CommandlineError,
    # HelpNeeded and VersionNeeded exceptions when necessary; if you want to
    # have these handled for you in the standard manner (e.g. show the help
    # and then exit upon an HelpNeeded exception), call your code from within
    # a block passed to this method.
    #
    # Note that this method will call System#exit after handling an exception!
    #
    # Usage example:
    #
    #   require 'optimist'
    #   p = Optimist::Parser.new do
    #     opt :monkey, "Use monkey mode"                     # a flag --monkey, defaulting to false
    #     opt :goat, "Use goat mode", :default => true       # a flag --goat, defaulting to true
    #   end
    #
    #   opts = Optimist::with_standard_exception_handling p do
    #     o = p.parse ARGV
    #     raise Optimist::HelpNeeded if ARGV.empty? # show help screen
    #     o
    #   end
    #
    # Requires passing in the parser object.
    #
    # pkg:gem/optimist#lib/optimist.rb:1275
    def with_standard_exception_handling(parser); end
  end
end

# Flag option.  Has no arguments. Can be negated with "no-".
#
# pkg:gem/optimist#lib/optimist.rb:996
class Optimist::BooleanOption < ::Optimist::Option
  # pkg:gem/optimist#lib/optimist.rb:998
  def initialize; end

  # pkg:gem/optimist#lib/optimist.rb:1002
  def flag?; end

  # pkg:gem/optimist#lib/optimist.rb:1003
  def parse(_paramlist, neg_given); end
end

# Thrown by Parser in the event of a commandline error. Not needed if
# you're using the Optimist::options entry.
#
# pkg:gem/optimist#lib/optimist.rb:15
class Optimist::CommandlineError < ::StandardError
  # pkg:gem/optimist#lib/optimist.rb:18
  def initialize(msg, error_code = T.unsafe(nil)); end

  # pkg:gem/optimist#lib/optimist.rb:16
  def error_code; end
end

# A Conflict constraint.  Useful when Option A cannot be used with Option B.
#
# pkg:gem/optimist#lib/optimist.rb:65
class Optimist::ConflictConstraint < ::Optimist::Constraint
  # pkg:gem/optimist#lib/optimist.rb:66
  def error_condition(overlap_size); end

  # pkg:gem/optimist#lib/optimist.rb:69
  def error_message(longargs); end
end

# Abstract class for a constraint.  Do not use by itself.
#
# pkg:gem/optimist#lib/optimist.rb:41
class Optimist::Constraint
  # pkg:gem/optimist#lib/optimist.rb:42
  def initialize(syms); end

  # pkg:gem/optimist#lib/optimist.rb:45
  def validate(given_args:, specs:); end
end

# Option class for handling multiple dates
#
# pkg:gem/optimist#lib/optimist.rb:1123
class Optimist::DateArrayOption < ::Optimist::DateOption
  # pkg:gem/optimist#lib/optimist.rb:1126
  def multi_arg?; end

  # pkg:gem/optimist#lib/optimist.rb:1125
  def type_format; end
end

# Option for dates.  Uses Chronic if it exists.
#
# pkg:gem/optimist#lib/optimist.rb:1073
class Optimist::DateOption < ::Optimist::Option
  # pkg:gem/optimist#lib/optimist.rb:1076
  def parse(paramlist, _neg_given); end

  # pkg:gem/optimist#lib/optimist.rb:1075
  def type_format; end
end

# A Dependency constraint.  Useful when Option A requires Option B also be used.
#
# pkg:gem/optimist#lib/optimist.rb:55
class Optimist::DependConstraint < ::Optimist::Constraint
  # pkg:gem/optimist#lib/optimist.rb:56
  def error_condition(overlap_size); end

  # pkg:gem/optimist#lib/optimist.rb:59
  def error_message(longargs); end
end

# An Either-Or constraint. For Mutually exclusive options
#
# pkg:gem/optimist#lib/optimist.rb:75
class Optimist::EitherConstraint < ::Optimist::Constraint
  # pkg:gem/optimist#lib/optimist.rb:76
  def error_condition(overlap_size); end

  # pkg:gem/optimist#lib/optimist.rb:79
  def error_message(longargs); end
end

# Regex for floating point numbers
#
# pkg:gem/optimist#lib/optimist.rb:35
Optimist::FLOAT_RE = T.let(T.unsafe(nil), Regexp)

# Option class for handling multiple Floats
#
# pkg:gem/optimist#lib/optimist.rb:1109
class Optimist::FloatArrayOption < ::Optimist::FloatOption
  # pkg:gem/optimist#lib/optimist.rb:1112
  def multi_arg?; end

  # pkg:gem/optimist#lib/optimist.rb:1111
  def type_format; end
end

# Floating point number option class.
#
# pkg:gem/optimist#lib/optimist.rb:1009
class Optimist::FloatOption < ::Optimist::Option
  # pkg:gem/optimist#lib/optimist.rb:1012
  def as_type(param); end

  # pkg:gem/optimist#lib/optimist.rb:1013
  def parse(paramlist, _neg_given); end

  # pkg:gem/optimist#lib/optimist.rb:1011
  def type_format; end
end

# Thrown by Parser if the user passes in '-h' or '--help'. Handled
# automatically by Optimist#options.
#
# pkg:gem/optimist#lib/optimist.rb:26
class Optimist::HelpNeeded < ::StandardError; end

# Option class for handling Files/URLs via 'open'
#
# pkg:gem/optimist#lib/optimist.rb:1130
class Optimist::IOArrayOption < ::Optimist::IOOption
  # pkg:gem/optimist#lib/optimist.rb:1133
  def multi_arg?; end

  # pkg:gem/optimist#lib/optimist.rb:1132
  def type_format; end
end

# Option class for handling IO objects and URLs.
# Note that this will return the file-handle, not the file-name
# in the case of file-paths given to it.
#
# pkg:gem/optimist#lib/optimist.rb:1041
class Optimist::IOOption < ::Optimist::Option
  # pkg:gem/optimist#lib/optimist.rb:1044
  def parse(paramlist, _neg_given); end

  # pkg:gem/optimist#lib/optimist.rb:1043
  def type_format; end
end

# Option class for handling multiple Integers
#
# pkg:gem/optimist#lib/optimist.rb:1102
class Optimist::IntegerArrayOption < ::Optimist::IntegerOption
  # pkg:gem/optimist#lib/optimist.rb:1105
  def multi_arg?; end

  # pkg:gem/optimist#lib/optimist.rb:1104
  def type_format; end
end

# Integer number option class.
#
# pkg:gem/optimist#lib/optimist.rb:1024
class Optimist::IntegerOption < ::Optimist::Option
  # pkg:gem/optimist#lib/optimist.rb:1027
  def as_type(param); end

  # pkg:gem/optimist#lib/optimist.rb:1028
  def parse(paramlist, _neg_given); end

  # pkg:gem/optimist#lib/optimist.rb:1026
  def type_format; end
end

# pkg:gem/optimist#lib/optimist.rb:693
class Optimist::LongNames
  # pkg:gem/optimist#lib/optimist.rb:694
  def initialize; end

  # long specified with :long has precedence over the true-name
  #
  # pkg:gem/optimist#lib/optimist.rb:718
  def long; end

  # pkg:gem/optimist#lib/optimist.rb:700
  def make_valid(lopt); end

  # all valid names, including alts
  #
  # pkg:gem/optimist#lib/optimist.rb:721
  def names; end

  # pkg:gem/optimist#lib/optimist.rb:709
  def set(name, lopt, alts); end
end

# pkg:gem/optimist#lib/optimist.rb:765
class Optimist::Option
  # pkg:gem/optimist#lib/optimist.rb:770
  def initialize; end

  # note: Option-Types with both multi_arg? and flag? false are single-parameter (normal) options.
  #
  # pkg:gem/optimist#lib/optimist.rb:803
  def array_default?; end

  # pkg:gem/optimist#lib/optimist.rb:807
  def callback; end

  # pkg:gem/optimist#lib/optimist.rb:767
  def default; end

  # pkg:gem/optimist#lib/optimist.rb:767
  def default=(_arg0); end

  # pkg:gem/optimist#lib/optimist.rb:808
  def desc; end

  # pkg:gem/optimist#lib/optimist.rb:805
  def doesnt_need_autogen_short; end

  # pkg:gem/optimist#lib/optimist.rb:819
  def educate; end

  # Indicates a flag option, which is an option without an argument
  #
  # pkg:gem/optimist#lib/optimist.rb:791
  def flag?; end

  # Format stdio like objects to a string
  #
  # pkg:gem/optimist#lib/optimist.rb:835
  def format_stdio(obj); end

  # Format the educate-line description including the default and permitted value(s)
  #
  # pkg:gem/optimist#lib/optimist.rb:827
  def full_description; end

  # pkg:gem/optimist#lib/optimist.rb:767
  def long; end

  # pkg:gem/optimist#lib/optimist.rb:767
  def long=(_arg0); end

  # pkg:gem/optimist#lib/optimist.rb:796
  def multi; end

  # pkg:gem/optimist#lib/optimist.rb:797
  def multi?; end

  # Indicates that this is a multivalued (Array type) argument
  #
  # pkg:gem/optimist#lib/optimist.rb:800
  def multi_arg?; end

  # pkg:gem/optimist#lib/optimist.rb:768
  def multi_given=(_arg0); end

  # pkg:gem/optimist#lib/optimist.rb:767
  def name; end

  # pkg:gem/optimist#lib/optimist.rb:767
  def name=(_arg0); end

  # pkg:gem/optimist#lib/optimist.rb:782
  def opts(key); end

  # pkg:gem/optimist#lib/optimist.rb:786
  def opts=(o); end

  # pkg:gem/optimist#lib/optimist.rb:812
  def parse(_paramlist, _neg_given); end

  # pkg:gem/optimist#lib/optimist.rb:767
  def permitted; end

  # pkg:gem/optimist#lib/optimist.rb:767
  def permitted=(_arg0); end

  # pkg:gem/optimist#lib/optimist.rb:767
  def permitted_response; end

  # pkg:gem/optimist#lib/optimist.rb:767
  def permitted_response=(_arg0); end

  # pkg:gem/optimist#lib/optimist.rb:868
  def permitted_type_valid?; end

  # pkg:gem/optimist#lib/optimist.rb:856
  def permitted_valid_string; end

  # incoming values from the command-line should be strings, so we should
  # stringify any permitted types as the basis of comparison.
  #
  # pkg:gem/optimist#lib/optimist.rb:886
  def permitted_value?(val); end

  # pkg:gem/optimist#lib/optimist.rb:810
  def required?; end

  # pkg:gem/optimist#lib/optimist.rb:767
  def short; end

  # pkg:gem/optimist#lib/optimist.rb:767
  def short=(_arg0); end

  # pkg:gem/optimist#lib/optimist.rb:792
  def single_arg?; end

  # provide type-format string.  default to empty, but user should probably override it
  #
  # pkg:gem/optimist#lib/optimist.rb:817
  def type_format; end

  # pkg:gem/optimist#lib/optimist.rb:875
  def validate_permitted(arg, value); end

  private

  # Generate the default value string for the educate line
  #
  # pkg:gem/optimist#lib/optimist.rb:845
  def default_description_str(str); end

  # Generate the permitted values string for the educate line
  #
  # pkg:gem/optimist#lib/optimist.rb:897
  def permitted_description_str(str); end

  class << self
    # Determines which type of object to create based on arguments passed
    # to +Optimist::opt+.  This is trickier in Optimist, than other cmdline
    # parsers (e.g. Slop) because we allow the +default:+ to be able to
    # set the option's type.
    #
    # pkg:gem/optimist#lib/optimist.rb:926
    def create(name, desc = T.unsafe(nil), opts = T.unsafe(nil), settings = T.unsafe(nil)); end

    # pkg:gem/optimist#lib/optimist.rb:976
    def get_klass_from_default(opts, opttype); end

    # pkg:gem/optimist#lib/optimist.rb:963
    def get_type_from_disdef(optdef, opttype, disambiguated_default); end

    # Provide a way to register symbol aliases to the Parser
    #
    # pkg:gem/optimist#lib/optimist.rb:913
    def register_alias(*alias_keys); end
  end
end

# Regex for parameters
#
# pkg:gem/optimist#lib/optimist.rb:38
Optimist::PARAM_RE = T.let(T.unsafe(nil), Regexp)

# The commandline parser. In typical usage, the methods in this class
# will be handled internally by Optimist::options. In this case, only the
# #opt, #banner and #version, #depends, and #conflicts methods will
# typically be called.
#
# If you want to instantiate this class yourself (for more complicated
# argument-parsing logic), call #parse to actually produce the output hash,
# and consider calling it from within
# Optimist::with_standard_exception_handling.
#
# pkg:gem/optimist#lib/optimist.rb:93
class Optimist::Parser
  # Initializes the parser, and instance-evaluates any block given.
  #
  # pkg:gem/optimist#lib/optimist.rb:136
  def initialize(*a, &b); end

  # Adds text to the help display. Can be interspersed with calls to
  # #opt to build a multi-section help page.
  #
  # pkg:gem/optimist#lib/optimist.rb:250
  def banner(s); end

  # Marks two (or more!) options as conflicting.
  #
  # pkg:gem/optimist#lib/optimist.rb:264
  def conflicts(*syms); end

  # Marks two (or more!) options as requiring each other. Only handles
  # undirected (i.e., mutual) dependencies. Directed dependencies are
  # better modeled with Optimist::die.
  #
  # pkg:gem/optimist#lib/optimist.rb:258
  def depends(*syms); end

  # The per-parser version of Optimist::die (see that for documentation).
  #
  # pkg:gem/optimist#lib/optimist.rb:553
  def die(arg, msg = T.unsafe(nil), error_code = T.unsafe(nil)); end

  # Print the help message to +stream+.
  #
  # pkg:gem/optimist#lib/optimist.rb:484
  def educate(stream = T.unsafe(nil)); end

  # Instead of displaying "Try --help for help." on an error
  # display the usage (via educate)
  #
  # pkg:gem/optimist#lib/optimist.rb:298
  def educate_on_error; end

  # Marks two (or more!) options as required but mutually exclusive.
  #
  # pkg:gem/optimist#lib/optimist.rb:270
  def either(*syms); end

  # A flag that determines whether or not to raise an error if the parser is passed one or more
  #  options that were not registered ahead of time.  If 'true', then the parser will simply
  #  ignore options that it does not recognize.
  #
  # pkg:gem/optimist#lib/optimist.rb:127
  def ignore_invalid_options; end

  # A flag that determines whether or not to raise an error if the parser is passed one or more
  #  options that were not registered ahead of time.  If 'true', then the parser will simply
  #  ignore options that it does not recognize.
  #
  # pkg:gem/optimist#lib/optimist.rb:127
  def ignore_invalid_options=(_arg0); end

  # The values from the commandline that were not interpreted by #parse.
  #
  # pkg:gem/optimist#lib/optimist.rb:118
  def leftovers; end

  # Define an option. +name+ is the option name, a unique identifier
  # for the option that you will use internally, which should be a
  # symbol or a string. +desc+ is a string description which will be
  # displayed in help messages.
  #
  # Takes the following optional arguments:
  #
  # [+:long+] Specify the long form of the argument, i.e. the form with two dashes. If unspecified, will be automatically derived based on the argument name by turning the +name+ option into a string, and replacing any _'s by -'s.
  # [+:short+] Specify the short form of the argument, i.e. the form with one dash. If unspecified, will be automatically derived from +name+. Use :none: to not have a short value.
  # [+:type+] Require that the argument take a parameter or parameters of type +type+. For a single parameter, the value can be a member of +SINGLE_ARG_TYPES+, or a corresponding Ruby class (e.g. +Integer+ for +:int+). For multiple-argument parameters, the value can be any member of +MULTI_ARG_TYPES+ constant. If unset, the default argument type is +:flag+, meaning that the argument does not take a parameter. The specification of +:type+ is not necessary if a +:default+ is given.
  # [+:default+] Set the default value for an argument. Without a default value, the hash returned by #parse (and thus Optimist::options) will have a +nil+ value for this key unless the argument is given on the commandline. The argument type is derived automatically from the class of the default value given, so specifying a +:type+ is not necessary if a +:default+ is given. (But see below for an important caveat when +:multi+: is specified too.) If the argument is a flag, and the default is set to +true+, then if it is specified on the the commandline the value will be +false+.
  # [+:required+] If set to +true+, the argument must be provided on the commandline.
  # [+:multi+] If set to +true+, allows multiple occurrences of the option on the commandline. Otherwise, only a single instance of the option is allowed. (Note that this is different from taking multiple parameters. See below.)
  # [+:permitted+] Specify an Array of permitted values for an option. If the user provides a value outside this list, an error is thrown.
  #
  # Note that there are two types of argument multiplicity: an argument
  # can take multiple values, e.g. "--arg 1 2 3". An argument can also
  # be allowed to occur multiple times, e.g. "--arg 1 --arg 2".
  #
  # Arguments that take multiple values should have a +:type+ parameter
  # drawn from +MULTI_ARG_TYPES+ (e.g. +:strings+), or a +:default:+
  # value of an array of the correct type (e.g. [String]). The
  # value of this argument will be an array of the parameters on the
  # commandline.
  #
  # Arguments that can occur multiple times should be marked with
  # +:multi+ => +true+. The value of this argument will also be an array.
  # In contrast with regular non-multi options, if not specified on
  # the commandline, the default value will be [], not nil.
  #
  # These two attributes can be combined (e.g. +:type+ => +:strings+,
  # +:multi+ => +true+), in which case the value of the argument will be
  # an array of arrays.
  #
  # There's one ambiguous case to be aware of: when +:multi+: is true and a
  # +:default+ is set to an array (of something), it's ambiguous whether this
  # is a multi-value argument as well as a multi-occurrence argument.
  # In thise case, Optimist assumes that it's not a multi-value argument.
  # If you want a multi-value, multi-occurrence argument with a default
  # value, you must specify +:type+ as well.
  #
  # pkg:gem/optimist#lib/optimist.rb:204
  def opt(name, desc = T.unsafe(nil), opts = T.unsafe(nil), &b); end

  # Parses the commandline. Typically called by Optimist::options,
  # but you can call it directly if you need more control.
  #
  # throws CommandlineError, HelpNeeded, and VersionNeeded exceptions.
  #
  # pkg:gem/optimist#lib/optimist.rb:356
  def parse(cmdline = T.unsafe(nil)); end

  # The complete configuration hashes for each option. (Mainly useful
  # for testing.)
  #
  # pkg:gem/optimist#lib/optimist.rb:122
  def specs; end

  # Defines a set of words which cause parsing to terminate when
  # encountered, such that any options to the left of the word are
  # parsed as usual, and options to the right of the word are left
  # intact.
  #
  # A typical use case would be for subcommand support, where these
  # would be set to the list of subcommands. A subsequent Optimist
  # invocation would then be used to parse subcommand options, after
  # shifting the subcommand off of ARGV.
  #
  # pkg:gem/optimist#lib/optimist.rb:284
  def stop_on(*words); end

  # Similar to #stop_on, but stops on any unknown word when encountered
  # (unless it is a parameter for an argument). This is useful for
  # cases where you don't know the set of subcommands ahead of time,
  # i.e., without first parsing the global options.
  #
  # pkg:gem/optimist#lib/optimist.rb:292
  def stop_on_unknown; end

  # Adds a synopsis (command summary description) right below the
  # usage line, or as the first line if usage isn't specified.
  #
  # pkg:gem/optimist#lib/optimist.rb:244
  def synopsis(s = T.unsafe(nil)); end

  # pkg:gem/optimist#lib/optimist.rb:253
  def text(s); end

  # Sets the usage string. If set the message will be printed as the
  # first line in the help (educate) output and ending in two new
  # lines.
  #
  # pkg:gem/optimist#lib/optimist.rb:238
  def usage(s = T.unsafe(nil)); end

  # Sets the version string. If set, the user can request the version
  # on the commandline. Should probably be of the form "<program name>
  # <version number>".
  #
  # pkg:gem/optimist#lib/optimist.rb:231
  def version(s = T.unsafe(nil)); end

  # pkg:gem/optimist#lib/optimist.rb:517
  def width; end

  # pkg:gem/optimist#lib/optimist.rb:539
  def wrap(str, opts = T.unsafe(nil)); end

  private

  # pkg:gem/optimist#lib/optimist.rb:649
  def collect_argument_parameters(args, start_at); end

  # yield successive arg, parameter pairs
  #
  # pkg:gem/optimist#lib/optimist.rb:572
  def each_arg(args); end

  # pkg:gem/optimist#lib/optimist.rb:317
  def handle_unknown_argument(arg, candidates, suggestions); end

  # pkg:gem/optimist#lib/optimist.rb:531
  def legacy_width; end

  # Match long variables with inexact match.
  # If we hit a complete match, then use that, otherwise see how many long-options partially match.
  # If only one partially matches, then we can safely use that.
  # Otherwise, we raise an error that the partially given option was ambiguous.
  #
  # pkg:gem/optimist#lib/optimist.rb:306
  def perform_inexact_match(arg, partial_match); end

  # pkg:gem/optimist#lib/optimist.rb:659
  def resolve_default_short_options!; end

  # pkg:gem/optimist#lib/optimist.rb:671
  def wrap_line(str, opts = T.unsafe(nil)); end

  class << self
    # The Option subclasses are responsible for registering themselves using this function.
    #
    # pkg:gem/optimist#lib/optimist.rb:99
    def register(lookup, klass); end

    # Gets the class from the registry.
    # Can be given either a class-name, e.g. Integer, a string, e.g "integer", or a symbol, e.g :integer
    #
    # pkg:gem/optimist#lib/optimist.rb:105
    def registry_getopttype(type); end
  end
end

# pkg:gem/optimist#lib/optimist.rb:129
Optimist::Parser::DEFAULT_SETTINGS = T.let(T.unsafe(nil), Hash)

# pkg:gem/optimist#lib/optimist.rb:727
class Optimist::ShortNames
  # pkg:gem/optimist#lib/optimist.rb:731
  def initialize; end

  # pkg:gem/optimist#lib/optimist.rb:738
  def add(values); end

  # pkg:gem/optimist#lib/optimist.rb:736
  def auto; end

  # pkg:gem/optimist#lib/optimist.rb:736
  def chars; end
end

# pkg:gem/optimist#lib/optimist.rb:729
Optimist::ShortNames::INVALID_ARG_REGEX = T.let(T.unsafe(nil), Regexp)

# Option class for handling multiple Strings
#
# pkg:gem/optimist#lib/optimist.rb:1116
class Optimist::StringArrayOption < ::Optimist::StringOption
  # pkg:gem/optimist#lib/optimist.rb:1119
  def multi_arg?; end

  # pkg:gem/optimist#lib/optimist.rb:1118
  def type_format; end
end

# Option class for handling Strings.
#
# pkg:gem/optimist#lib/optimist.rb:1063
class Optimist::StringOption < ::Optimist::Option
  # pkg:gem/optimist#lib/optimist.rb:1065
  def as_type(val); end

  # pkg:gem/optimist#lib/optimist.rb:1067
  def parse(paramlist, _neg_given); end

  # pkg:gem/optimist#lib/optimist.rb:1066
  def type_format; end
end

# pkg:gem/optimist#lib/optimist.rb:11
Optimist::VERSION = T.let(T.unsafe(nil), String)

# Thrown by Parser if the user passes in '-v' or '--version'. Handled
# automatically by Optimist#options.
#
# pkg:gem/optimist#lib/optimist.rb:31
class Optimist::VersionNeeded < ::StandardError; end
