inherit_gem:
  rubocop-sorbet: config/rbi.yml

require:
 - rubocop-rake
 - rubocop-rspec
 - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Lint/EmptyFile:
  Exclude:
    - 'sorbet/rbi/gems/*.rbi'

Gemspec:
  Enabled: true
