name: Rake

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
    - uses: actions/checkout@v7
    - uses: jdx/mise-action@v4
    - run: mise run install
    - run: mise run lint
    - if: ${{ runner.os != 'Windows' && env.CC_TEST_REPORTER_ID != '' }}
      uses: paambaati/codeclimate-action@v9.0.0
      with:
        coverageCommand: mise run test
        debug: true
    - if: ${{ runner.os == 'Windows' || env.CC_TEST_REPORTER_ID == '' }}
      run: mise run test
